
version: '2'
services:
  redis:
    image: redis
    restart: always
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - /srv/pgr/db:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  pgr:
    image: lcasuol/pgr_system:lcas
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    #build: . 
    command: "bash -c 'ln -fs /srv/config/.env /var/www/html/pgr/.env && /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf'"
    links:
      - db
      - redis
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/pgr/storage:/var/www/html/pgr/storage
      - /srv/pgr/config:/srv/config

  smtp:
    environment:
      - MH_HOSTNAME=pgr.lcas.group
      - MH_UI_WEB_PATH=mailhog
      - MH_MAILDIR_PATH=/srv/mailhog/maildir
      - MH_OUTGOING_SMTP=/srv/mailhog/config/outgoing.json
      - MH_STORAGE=maildir
    image: mailhog/mailhog
    command: ["-smtp-bind-addr", "0.0.0.0:25"]
    user: root
    volumes:
      - /srv/mailhog:/srv/mailhog
    expose:
      - 25
      - 8025
    ports:
      - "8025:8025"
      - "8825:25"

  mysqldump:
    image: schnitzler/mysqldump
    restart: always
    volumes:
      - ./db-backup.sh:/etc/periodic/daily/backup
      - /srv/pgr/storage:/backup
    command: ["-l", "8", "-d", "8"]
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: pgr_saml

