
version: '2'
services:
  redis:
    image: redis
  db:
    image: mysql
    volumes:
      - /srv/pgr/db:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  pgr:
    build: . 
    command: "bash -c 'ln -fs /srv/config/.env /var/www/html/pgr/.env && /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf'"
    links:
      - db
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/pgr/storage:/var/www/pgr/storage
      - /srv/pgr/config:/srv/config
