
version: '2'
services:
  redis:
    image: redis
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - /srv/pgr/db:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  pgr:
    image: lcasuol/pgr_devel:latest
    build:
      context: .
      dockerfile: Dockerfile.devel
    #build: . 
    command: "bash -c '/usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf'"
    links:
      - db
      - redis
    ports:
      - 19989:80
      - 19443:443
    volumes:
      - .:/var/www/html/pgr

  mysqldump:
    image: schnitzler/mysqldump
    volumes:
      - ./db-backup.sh:/etc/periodic/daily/backup
      - /srv/pgr/storage:/backup
    command: ["-l", "8", "-d", "8"]
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: pgr_saml

