
version: '2'
services:
  redis:
    image: redis
  db:
    image: mysql
    volumes:
      - pgrdb:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  pgr_devel:
    build: 
      context: .
      dockerfile: Dockerfile.devel 
    command: "bash -c 'ln -fs /srv/config/.env /var/www/html/pgr/.env && /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf'"
    links:
      - db
    ports:
      - 9989:80
    volumes:
      - .:/var/www/html/pgr/
      - pgrdata:/var/www/pgr/storage
      - /srv/pgr/config:/srv/config
volumes:
  pgrdata: 
  pgrdb: 
